#!/bin/bash
set -e

# init default values
emulatorName=android-17-basic

function log {
	local logStart="#"
	local sourceLen=${#BASH_SOURCE[@]}
	for ((i=$sourceLen-1; i>0; --i)); do
		logStart="$logStart [$(basename ${BASH_SOURCE[$i]})]"
	done
	echo "$logStart $@"
}

function TODO {
	log "[TODO] $@"
	log "[TODO] terminating."
	exit 1
}

